name: Build Flutter Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-flutter-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
        channel: 'stable'
        cache: true
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools: 34.0.0
        
    - name: Check versions
      run: |
        flutter --version
        flutter doctor -v
        java -version
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        
    - name: Fix Android Embedding v1 Issue  
      run: |
        cd ios_camera_flutter_app
        echo "=== Before fix ==="
        ls -la android/app/src/main/
        
        echo "=== Force recreate Android project with v2 embedding ==="
        # This completely recreates Android folder with proper v2 embedding
        rm -rf android
        flutter create --platforms android --org com.iosCamera ios_camera_flutter_app_temp
        mv ios_camera_flutter_app_temp/android ./android
        rm -rf ios_camera_flutter_app_temp
        
        echo "=== After recreation ==="
        ls -la android/app/src/main/
        cat android/app/src/main/AndroidManifest.xml
        
    - name: Build APK with v2 Embedding
      run: |
        cd ios_camera_flutter_app
        flutter clean
        flutter pub get
        yes | flutter doctor --android-licenses 2>/dev/null || echo "Licenses accepted"
        flutter build apk --release --verbose
        
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: camera-app-release-apk
        path: ios_camera_flutter_app/build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30
        if-no-files-found: error
        
    - name: Build Flutter APK (Debug)
      run: |
        cd ios_camera_flutter_app
        flutter build apk --debug
        
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: camera-app-debug-apk
        path: ios_camera_flutter_app/build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 30
        if-no-files-found: warn